version: '3'
services:
  homeapp-mysql:
    image: "hypriot/rpi-mysql"
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - /home/pi/Applications/homeapp/docker/mysql/mysql_data:/var/lib/mysql
      - /home/pi/Applications/homeapp/docker/mysql/mysql_init:/docker-entrypoint-initdb.d
