version: '3'
services:
  homeapp-mysql:
    image: "mysql"
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_init:/docker-entrypoint-initdb.d
