- action:
  - data_template:
      payload: >
                {
                  "name": "MotionOn",
                  "id": "sensor.aeotec_zw100_multisensor_6_burglar_6",
                  "state":  {{ states('sensor.aeotec_zw100_multisensor_6_burglar_6')}},
                  "unitOfMeasurement": ""
                 }
      topic: homeassistant/motion-on
    service: mqtt.publish
  alias: MotionOn
  condition: []
  trigger:
  - above: '7'
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6
    platform: numeric_state
- action:
  - data_template:
      payload: >
                {
                  "name": "TamperOn",
                  "id": "sensor.aeotec_zw100_multisensor_6_burglar_6",
                  "state":  {{ states('sensor.aeotec_zw100_multisensor_6_burglar_6')}},
                  "unitOfMeasurement": ""
                }
      topic: homeassistant/tamper-on
    service: mqtt.publish
  alias: Tamper
  condition: []
  trigger:
  - above: '2'
    below: '4'
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6
    platform: numeric_state
- action:
  - data_template:
      payload: >
                {
                  "name": "MotionOff",
                  "id": "sensor.aeotec_zw100_multisensor_6_burglar_6",
                  "state":  {{ states('sensor.aeotec_zw100_multisensor_6_burglar_6')}},
                  "unitOfMeasurement": ""
                }
      topic: homeassistant/motion-off
    service: mqtt.publish
  alias: MotionOff
  condition: []
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6
    from: '8'
    to: '0'
    platform: state
- action:
  - data_template:
      payload: >
                {
                   "name": "TamperOff",
                   "id": "sensor.aeotec_zw100_multisensor_6_burglar_6",
                   "state": {{ states('sensor.aeotec_zw100_multisensor_6_burglar_6')}},
                   "unitOfMeasurement": ""
                }
      topic: homeassistant/tamper-off
    service: mqtt.publish
  alias: TamperOff
  condition: []
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6
    from: '3'
    to: '0'
    platform: state
- action:
  - data_template:
      payload: >
                {
                   "name": "Temperature",
                   "id": "sensor.aeotec_zw100_multisensor_6_temperature_7",
                   "state": {{ states('sensor.aeotec_zw100_multisensor_6_temperature_7')}},
                   "unitOfMeasurement": "°C"
                }
      topic: homeassistant/temperature
    service: mqtt.publish
  alias: Temperature
  condition: []
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_temperature_7
    platform: state
- action:
  - data_template:
      payload: >
                {
                   "name": "Humidity",
                   "id": "sensor.aeotec_zw100_multisensor_6_relative_humidity_7",
                   "state": {{ states('sensor.aeotec_zw100_multisensor_6_relative_humidity_7')}},
                   "unitOfMeasurement": "%"
                }
      topic: homeassistant/humidity
    service: mqtt.publish
  alias: Humidity
  condition: []
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_relative_humidity_7
    platform: state
- action:
  - data_template:
      payload: >
                {
                  "name": "Ultraviolet",
                  "id": "sensor.aeotec_zw100_multisensor_6_ultraviolet_7",
                  "state": {{ states('sensor.aeotec_zw100_multisensor_6_ultraviolet_7') }},
                  "unitOfMeasurement": ""
                }
      topic: homeassistant/ultraviolet
    service: mqtt.publish
  alias: Ultraviolet
  condition: []
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_ultraviolet_7
    platform: state
- action:
  - data_template:
      payload: >
                {
                  "name": "Luminance",
                  "id": "sensor.aeotec_zw100_multisensor_6_luminance_7",
                  "state": {{ states('sensor.aeotec_zw100_multisensor_6_luminance_7')}},
                  "unitOfMeasurement": "Lux"
                }
      topic: homeassistant/luminance
    service: mqtt.publish
  alias: Luminance
  condition: []
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_luminance_7
    platform: state

# Pushbullet
#- action:
#  - data_template:
#      message: >
#                {
#                  "name": "MotionOnPush"
#                 }
#    service: notify.NOTIFY_ME
#  alias: MotionOnPush
#  condition: []
#  trigger:
#  - above: '7'
#    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6
#    platform: numeric_state
#- action:
#  - data_template:
#      message: >
#                {
#                  "name": "TamperOnPush",
#                }
#    service: notify.NOTIFY_ME
#  alias: TamperOnPush
#  condition: []
#  trigger:
#  - above: '2'
#    below: '4'
#    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6
#    platform: numeric_state